/*
 * HmGoogleGeminiWeb v 1.1.1.5
 *
 * Copyright (c) 2025 Akitsugu Komiyama
 * under the MIT License
 */


hidemaruversion "9.39.99";

setcompatiblemode 0x08000000;

jsmode  @"WebView2\HmGoogleGeminiWeb";

js {

// ------------- 会話エンジンの設定項目 -------------

const baseUrl = "https://gemini.google.com/app";

const renderPaneCustomParam = {
    place: "rightside",            // leftside | rightside | upside | downside
    size: 900,                     // 左や右の配置の時は、横幅のこと。上や下の配置の時は縦幅のこと。
};

const isOneAtTimeAIRenderPane = 1; // AI関連のレンダリング枠は(他の種類のAIも含め)１つだけにする。(複数起動しそうになると、前のものが閉じる）

// --------------------------------------------------

const renderPaneTargetName = "HmGoogleGeminiWeb";

const currentMacroDirectory = currentmacrodirectory();

const script = hidemaru.loadTextFile(currentMacroDirectory + "\\HmConvAIWeb.js");
eval(script);

const [major,minor,build] = hidemaruversion().split(".");

// v9.50β4以降では、フォーカスに比較的自由に当てられる
if (version() >= 950 && build >= 4) {
    function onPrevKeySendDecorator() {
        
        try {
            // Geminiのインプット枠へのフォーカス。手堅いが将来変更になるかも。だめなようなら、下のリフレッシュする処理にながさないとだめかも。
            browserpanecommand({target:"_each", focusinputfield:'[contenteditable="true"]'});
        } catch(e) {
        }
    }

} else {

    // InputFieldへのフォーカスに失敗したらリフレッシュ
    // (これでGeminiが自動で Input フィールドにフォーカスを移動してくれる)
    function focusInputFailDecorator() {
        browserpanecommand({target:"_each", "refresh":1});
    }
}

doMain();

}
